# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: board.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62oard.proto\x12\x04game\"&\n\x05\x42oard\x12\x1d\n\x07squares\x18\x01 \x03(\x0e\x32\x0c.game.square*)\n\x06square\x12\t\n\x05\x45MPTY\x10\x00\x12\t\n\x05MARK1\x10\x01\x12\t\n\x05MARK2\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'board_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SQUARE']._serialized_start=61
  _globals['_SQUARE']._serialized_end=102
  _globals['_BOARD']._serialized_start=21
  _globals['_BOARD']._serialized_end=59
# @@protoc_insertion_point(module_scope)
